spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password:
    #url: jdbc:postgresql://mouse.db.elephantsql.com/buqbaoxn
    #username: buqbaoxn
    #password: ofl2aZ5Yo5ydUpu8KIOV94Saw9h55Eo4
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true